### ISSUE TITLE
ExportLabeledText.php is commited truncated

### ISSUE THREAD

**Issue by brunetton** [ideesculture/museesDeFrance#5]
Hi,

`/export-joconde/ExportLabeledText.php` seems to have been commited truncated.

**Comment by gautiermichelin** [comment]
As we are in a french-only zone (no external country uses such antideluvian export format), let's switch to french.

J'ai ajouté les deux lignes manquantes en fin de fichier. A noter, on est pas prêt d'avoir fini la validation SMF pour l'export Joconde, on a eu un retour d'expertise hier, ceci va également certainement impacter la structure Joconde (refonte complète de la gestion des champs date).

Pas eu de réponse à mon mail à part ça ? :-)

**Comment by gautiermichelin** [comment]
https://github.com/ideesculture/museesDeFrance/commit/8abac6daaa3d54e8cf869ea5558353dc0fde43b8

**Comment by brunetton** [comment]
Hello ! 
Ce n'est pas une bonne nouvelle pour la validation; nous en reparlerons ensemble je suis sûr. Pris sur d'autres sujets brûlants depuis quelques jours, nous n'avons pas eu le temps de répondre encore. Cela ne saurait tarder !
Une petite rencontre téléphonique sera également intéressante je pense.
A bientôt donc

**Comment by gautiermichelin** [comment]
En fait, si, c'est une excellente nouvelle, puisque la validation suit son cours, et qu'on est proche de la validation au bout de plus d'un an de boulot avec le Musée de Saint Maur des Fossés :-)

L'info était plutôt que là, tu as un bout de chemin, mais pas tout, et que ça va changer. Ca évite de tout reprendre bien sûr. Le paramétrage, au delà du code, ne sera pas à piquer des hannetons toutefois.

Par ailleurs, j'ai bien eu la réponse de Pierre-Yves Dillard, merci d'avoir fait passer l'information.
