### ISSUE TITLE
/index.php/museesDeFrance/InstallProfileThesaurus/Index - 'continue' not in the 'loop' or 'switch' context in /home/bruno/dev/ee/collectiveaccess/tmp/tests_thesaurus/museesDeFrance-master/lib/migration_functionlib.php on line 339

### ISSUE THREAD

**Issue by brunetton** [ideesculture/museesDeFrance#6]
Hi

With the last commit in master (8abac6d), going to "procédures réglementaires" => "installation" doesn't work anymore: 

    /index.php/museesDeFrance/InstallProfileThesaurus/Index - 'continue' not in the 'loop' or 'switch' context in /home/bruno/dev/ee/collectiveaccess/tmp/tests_thesaurus/museesDeFrance-master/lib/migration_functionlib.php on line 339

**Comment by brunetton** [comment]
To reproduce, simply include the file

**Comment by gautiermichelin** [comment]
Should have been corrected, no problem for last months.
