### ISSUE TITLE
Installation : profile validation failed.

### ISSUE THREAD

**Issue by papposilene** [ideesculture/museesDeFrance#7]
Lors de la tentative d'installation du profil (en écrasant une ancienne configuration après avoir activé l'option "CA_ALLOW_INSTALLER_TO_OVERWRITE_EXISTING_INSTALLS"), la page d'installation de Providence (version 1.7.5) m'indique que : "There were errors parsing the profile(s): Profile validation failed. Your profile doesn't conform to the required XML schema." Pourtant, j'ai bien enregistré le fichier et le parser de Komodo Edit ne semble pas trouver de problème...

**Comment by gautiermichelin** [comment]
Il faut recopier à la fois le profil (xml) et le fichier de validation (profile.xsd) dans le répertoire d'installation. Cela devrait résoudre le problème.
